FROM almalinux:9
ADD https://raw.githubusercontent.com/karthikkandagaddala/Shell-Script/refs/heads/main/04-Specialvariables.sh /tmp/04-Specialvariables.txt
CMD ["sleep","60"]
#tar files also we can simply untar by using ADD